In [53]:
import cv2 
import numpy as np 
import matplotlib.pyplot as plt 

def extract_color(event,x,y,flags,param) :
    if event==cv2.EVENT_LBUTTONDOWN : 
        lower_bound=hsv_im[y,x].astype(np.uint8)
        higher_bound=lower_bound+np.array([20,20,20]).astype(np.uint8)
        print(higher_bound)
        print(lower_bound)
        mask=cv2.inRange(hsv_im,lower_bound,higher_bound)
        result=cv2.bitwise_and(im,im,mask=mask)
        cv2.imshow("result",result)
        





im=cv2.imread("bunny.jpeg")
hsv_im=cv2.cvtColor(im,cv2.COLOR_BGR2HSV)
cv2.namedWindow("image") 
cv2.setMouseCallback("image",extract_color)

while True : 

    cv2.imshow("image",im)

    key=cv2.waitKey(1)
    if key==27 : 
        break 

cv2.destroyAllWindows() 


[20 19 90]
[  0 255  70]
[ 33  33 161]
[ 13  13 141]
[23 19 96]
[  3 255  76]
[44 40 83]
[24 20 63]
[ 42  50 230]
[ 22  30 210]
[ 40  51 168]
[ 20  31 148]
[21 19 56]
[  1 255  36]
[ 20  19 143]
[  0 255 123]
[25  7  7]
[  5 243 243]
[ 23 250 193]
[  3 230 173]
[116  29 156]
[ 96   9 136]
[185  23 168]
[165   3 148]
[23 18  2]
[  3 254 238]
[23 19 96]
[  3 255  76]
[ 25  12 246]
[  5 248 226]
[21 19 52]
[  1 255  32]
[ 24 247   5]
[  4 227 241]
[ 24 232 133]
[  4 212 113]
[152 179  28]
[132 159   8]
[ 23 233 247]
[  3 213 227]
[ 22 225 193]
[  2 205 173]
[ 23 231 242]
[  3 211 222]
[ 24 242 254]
[  4 222 234]
[25  4  1]
[  5 240 237]
[25 10  1]
[  5 246 237]
[20 19 90]
[  0 255  70]
[ 23  16 209]
[  3 252 189]
[ 24 249 243]
[  4 229 223]


In [14]:
# cap=cv2.VideoCapture(0)

# while True : 
#     ret , frame = cap.read()

#     hsv_image=cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)

#     lower_bound=np.array([90,50,50])
#     higher_bound=np.array([130,255,255])

#     mask=cv2.inRange(hsv_image,lower_bound,higher_bound)

#     result=cv2.bitwise_and(frame,frame,mask=mask) 
    
#     cv2.imshow("frame",result)

#     key=cv2.waitKey(10)
#     if key==27 : 
#         break
# cap.release()
# cv2.destroyAllWindows()
